fastlane_require 'dotenv'

before_all do
  Dotenv.overload '.env.secret'
end

lane :internal do
  changeEnv('staging')
  versionName = increaseVersion
  gradle(task: 'clean')
  gradle(task: 'bundle', build_type: 'Release')
  upload_to_play_store(
    track: 'internal',
    skip_upload_apk: true
  )
  notifySlack(versionName)
end

def increaseVersion()
  ensure_git_status_clean

  # read file
  path = '../app/build.gradle'
  s = File.read(path)
  # update version code
  re = /versionCode\s+(\d+)/ 
  s = s.sub(re, "versionCode #{getNextVersionCode}")
  # update version name
  re = /versionName\s+"(\d{2}\.\d{2}\.\d{2})(?:\.(\d+))?"/
  versionName = getNextVersionName
  s = s.sub(re, "versionName \"#{versionName}\"")
  # save to file
  f = File.new(path, 'w')
  f.write(s)
  f.close
  # commit
  git_commit(path: 'app/build.gradle', message: "Stg Version Bump #{versionName}")
  push_to_git_remote(remote_branch: 'master')
  return versionName
end

def notifySlack(versionName)
  message = "New internal version (#{versionName}) of Park Smart Android has been deployed successfully. Please download it <https://play.google.com/store/apps/details?id=com.psad_mobile|here>"
  slack(
    message: message,
    slack_url: ENV['DEV_CHANNEL_SLACK_URL'],
    success: true,
    default_payloads: []
  )
end

def getLatestVersionName()
  productionName = google_play_track_release_names(track: 'production')[0]
  internalName = google_play_track_release_names(track: 'internal')[0]
  re = /^(\d{2}\.\d{2}\.\d{2})(?:\.(\d+))?$/
  iMatch = internalName.match(re)
  pMatch = productionName.match(re)
  # if version names isn't follow format
  if !pMatch && !iMatch
    return nil
  elsif !iMatch && pMatch != nil
    return productionName
  elsif !pMatch && iMatch != nil
    return internalName
  end
  # if both follow format
  iDate = iMatch[1].gsub('.', '').to_i
  pDate = pMatch[1].gsub('.', '').to_i
  # compare date
  if pDate > iDate
    return productionName
  elsif pDate < iDate
    return internalName
  end
  # if same date
  if pMatch[1].to_i > iMatch[1].to_i
    return productionName
  else
    return internalName
  end
end

def getNextVersionCode()
  productionCode = google_play_track_version_codes(track: 'production')
  internalCode = google_play_track_version_codes(track: 'internal')
  return ([productionCode[0], internalCode[0]].max + 1).to_s
end

def getNextVersionName()
  dateNow = Time.now.strftime("%y.%m.%d")
  latestName = getLatestVersionName
  if !latestName
    return dateNow
  end
  re = /^(\d{2}\.\d{2}\.\d{2})(?:\.(\d+))?$/
  m = latestName.match(re)
  currentDate = m[1]
  currentPatch = m[2]
  nextPatch = ""
  if dateNow != currentDate
    nextPatch = ""
  elsif currentPatch
    nextPatch = "." + (currentPatch.to_i + 1).to_s
  else
    nextPatch = ".2"
  end
  return dateNow + nextPatch
end

def changeEnv(env)
  f = File.new('../../.env', 'w')
  apiUrl = "#{env.upcase}_API_URL"
  content = "API_URL=#{ENV[apiUrl]}
ENVIRONMENT=#{env}
ENABLE_REDUX_LOGGER=#{env == 'production' ? 'false' : 'true'}"
  f.write(content)
  f.close
end